### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by atsushi59** [atsushi59/Playground-search#91]
### 実装予定の機能
- [ ] Geolocation API、Geocoding API、Google Maps JavaScript APIを使用して位置情報（住所）を取得  
- [ ] 取得した住所とGPT-4 APIを使用して選択ボタンからの検索
- [ ] Directions API、NAVITIME Route(totalnavi)APIを使用しルートの時間を取得
- [ ] 検索結果からPlaces APIを用いて名前、住所、営業時間、公式HP、Directions API等で取得したルートの時間を表示
- [ ] ユーザーが選択した時間内でなければ場所の表示をしないように制限
- [ ] GPT-4で提示された場所の営業時間とHPどちらも情報を取得できない場合は表示しないように制限
- [ ] 検索結果からユーザーが行く場所を選択した場合Google Mapsに移動し、ナビゲーションまたは乗換案内ページを表示

### 必要なページ
- [ ] TOPページ（検索するページ）(static_top)
- [ ] 検索結果を表示するページ(search/index)
- [ ] 再検索ページ(search/search)
- [ ] プライバシーポリシーページ
- [ ] 利用規約ページ
- [ ] お問い合わせページ

### その他
#45まででMVPリリースとなります(ストーリーポイント計72)

ご確認の程よろしくお願い致します

**Comment by tmtkzk0823** [comment]
概ね良さそうです！
LGTMです！
